backend:
  name: Python Template
  description: a starting python service
  env: local

  server:
    host: "0.0.0.0"
    port: 4000
    path: "/py-svc"
    allowedOrigins:
      - "http://localhost:3000"
